### ISSUE TITLE
PHP Errors when activating pax-fax in Nextcloud

### ISSUE THREAD

**Issue by marno2703** [DoubleBastionAdmin/pax-fax#1] opened 2022-04-14 13:09 UTC
After activation pax-fax I get these errors multiple time a second:

```
[PHP] Error: Undefined offset: 1 at /usr/local/www/vhosts/xxx/webroot/apps/pax_fax/lib/AppInfo/Application.php#39

/usr/local/www/vhosts/xxx/webroot/apps/pax_fax/lib/AppInfo/Application.php - line 39:
OC\Log\ErrorHandler::onError(8, "Undefined offset: 1", "/usr/local/ ... p", 39, { file: "/us ... ]})
```

and

```
[pax_fax] Fatal: Error during app service registration: explode() expects parameter 2 to be string, null given

/usr/local/www/vhosts/xxx/webroot/apps/pax_fax/lib/AppInfo/Application.php - line 39:
explode("(", null)
```

PHP 7.3 
Apache 2.4
FreeBSD

**Comment by DoubleBastionAdmin** [comment] 2022-04-14 15:14
The errors that you mention above are likely to be caused by the fact that the command `timedatectl | grep zone` which is used in the `Application.php` file to get the timezoe of the server, so that Pax Fax can show the correct time when faxes are sent/received, has a different output on FreeBSD than on Debian and other related Linux distributions. Please run `timedatectl | grep zone` on your server and post the output if you can.

**Comment by marno2703** [comment] 2022-04-14 15:16
timedatectl is not available on freebsd

**Comment by DoubleBastionAdmin** [comment] 2022-04-14 16:13
Ok. I just changed the way it gets the timezone, so that it's independent of the operating system. Until a new updated version of Pax Fax is released tomorrow, to solve the errors from above, please replace the content of the `pax_fax/lib/AppInfo/Application.php` file with the following content:
```
<?php
/**
 * @copyright 2021 Double Bastion LLC <www.doublebastion.com>
 *
 * @author Double Bastion LLC
 *
 * @license GNU AGPL version 3 or any later version
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU AFFERO GENERAL PUBLIC LICENSE for more details.
 *
 * You should have received a copy of the GNU Affero General Public
 * License along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

declare(strict_types=1);

namespace OCA\PaxFax\AppInfo;

use OCP\AppFramework\App;
use OCP\IServerContainer;
use OCA\PaxFax\Controller\PageController;


if ((@include_once __DIR__ . '/../../Phaxio/vendor/autoload.php') === false) {
     throw new Exception('Cannot include autoload. Did you run install dependencies using composer?');
}

class Application extends App {

	public function __construct(array $urlParams=array()) {
		  parent::__construct('pax_fax', $urlParams);

           $container = $this->getContainer();

           // Controllers
           $container->registerService('PageController', function($c) {
              return new PageController(
                  $c->query('AppName'),
                  $c->query('Request')
              );
           });

	}

        public function register() {

                  $gettimezone = \OC::$server->getConfig()->getSystemValue('logtimezone', 'UTC');
                  date_default_timezone_set($gettimezone);

		  $server = $this->getContainer()->getServer();

 	          $app = new \OCA\PaxFax\AppInfo\Application();
		  $app->register();
        }

}

```

**Comment by DoubleBastionAdmin** [comment] 2022-04-14 16:21
Please note that for the solution from above to work, you will have to have the `logtimezone` parameter set in your `webroot/config/config.php` file like this: `'logtimezone' => 'Europe/Berlin',` or `'logtimezone' => 'Europe/London'`, or whatever your timezone is. The possible timezones that can be set in the Nextcloud configuration file can be found [here](https://www.php.net/manual/en/timezones.php).

**Comment by DoubleBastionAdmin** [comment] 2022-04-14 21:11
A new version of Pax Fax has been pushed to the Nextcloud app store, but it will become available for automatic updates probably tomorrow.
You can test sending and receiving faxes with Pax Fax by sending a fax to your own number.
If you have any other problems please, post them here. Otherwise, you can close this issue.

**Comment by DoubleBastionAdmin** [comment] 2022-04-15 10:00
The new version of Pax Fax, 1.0.3, is now available to update to from inside Nextcloud. If there are no other problems, this issue will be closed.

**Closed as completed** 2022-04-16 10:08 UTC
